### ISSUE TITLE
cross origin restrictions

### ISSUE THREAD

**Issue by Underdog-01** [jamesrwhite/unity-kick-ups#1]
You can't use cross-origin loading of images & files.
Also the google api font library file you attempted to use no longer resides at the address.
You can use Cloudflare to host it but I do not see the point. It is better to just include the relevant js library in the game files itself.

If you continue the project, stop loading 3rd party files & include all of what is needed locally.

**Comment by jamesrwhite** [comment]
Not really sure what you're referring to here? None of what you describe is in this repo.

This is very much not an active project though, it's something I made for fun whilst learning Unity 6 years ago.
